"""
Generates a compact clinic data string for embedding in the CF Worker system prompt.
Run: python3 generate_clinic_data.py
Output: src/clinic_data.js
"""
import csv
import json
import os

CSV_PATH = "../rehab-online-scraper/clinics_enriched.csv"
OUT_PATH = "src/clinic_data.js"

def clean(val):
    if not val or val in ("None", "[]", "{}", "nan"):
        return ""
    return str(val).strip()

def fmt_list(val):
    try:
        items = json.loads(val.replace("'", '"'))
        if isinstance(items, list):
            return ", ".join(str(i) for i in items if i)
    except Exception:
        pass
    return clean(val)

rows = []
with open(CSV_PATH, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        rows.append(row)

lines = []
for r in rows:
    name = clean(r.get("title", ""))
    website = clean(r.get("website", ""))
    address = clean(r.get("address", ""))
    postcode = clean(r.get("postcode", ""))
    location = fmt_list(r.get("locations", "")) or postcode
    cost = fmt_list(r.get("cost", ""))
    payment = fmt_list(r.get("payment", ""))
    insurance = fmt_list(r.get("insurance_networks", ""))
    detox = clean(r.get("detox_on_site", ""))
    gender = clean(r.get("gender_model", ""))
    faith = clean(r.get("is_faith_based", ""))
    faith_trad = clean(r.get("faith_tradition", ""))
    min_age = clean(r.get("min_age", ""))
    rating = clean(r.get("regulatory_rating", ""))
    reg_body = clean(r.get("regulatory_body", ""))
    modalities = fmt_list(r.get("named_modalities", ""))
    addictions = fmt_list(r.get("addictions_treated", ""))
    rehab_type = fmt_list(r.get("rehab_type", ""))
    accessibility = fmt_list(r.get("accessibility", ""))
    setting = clean(r.get("setting", ""))
    aftercare = clean(r.get("aftercare", ""))[:180]
    family = clean(r.get("has_family_programme", ""))
    pricing_clean = clean(r.get("pricing_clean", ""))[:120]
    capacity = clean(r.get("capacity", ""))
    desc = clean(r.get("description", ""))[:200]
    ai_summary = clean(r.get("ai_summary", ""))

    parts = [f"NAME: {name}"]
    if website:
        parts.append(f"WEBSITE: {website}")
    if address:
        parts.append(f"ADDRESS: {address}")
    if location:
        parts.append(f"REGION: {location}")
    if cost:
        parts.append(f"COST: {cost}")
    if payment:
        parts.append(f"PAYMENT: {payment}")
    if insurance:
        parts.append(f"INSURANCE: {insurance}")
    if detox and detox not in ("None", ""):
        parts.append(f"DETOX: {detox}")
    if gender and gender != "unconfirmed":
        parts.append(f"GENDER: {gender}")
    if faith == "True":
        parts.append(f"FAITH: {faith_trad or 'Yes'}")
    if min_age:
        parts.append(f"MIN_AGE: {min_age}")
    if reg_body and rating:
        parts.append(f"RATING: {reg_body} - {rating}")
    elif rating:
        parts.append(f"RATING: {rating}")
    if modalities:
        parts.append(f"THERAPIES: {modalities}")
    if addictions:
        parts.append(f"TREATS: {addictions}")
    if rehab_type:
        parts.append(f"TYPE: {rehab_type}")
    if accessibility:
        parts.append(f"ACCESSIBILITY: {accessibility}")
    if setting:
        parts.append(f"SETTING: {setting}")
    if capacity:
        parts.append(f"CAPACITY: {capacity} beds")
    if aftercare:
        parts.append(f"AFTERCARE: Yes")
    if family == "True":
        parts.append(f"FAMILY_PROGRAMME: Yes")
    if pricing_clean:
        parts.append(f"PRICING: {pricing_clean}")
    if ai_summary:
        parts.append(f"SUMMARY: {ai_summary}")
    elif desc:
        parts.append(f"ABOUT: {desc}")

    lines.append("\n".join(parts))

clinic_data = "\n\n---\n\n".join(lines)

# Estimate token count (rough: 4 chars per token)
chars = len(clinic_data)
print(f"Clinic data: {chars} chars, ~{chars//4} tokens across {len(rows)} clinics")

js_content = f"""// Auto-generated by generate_clinic_data.py — do not edit manually
export const CLINIC_DATA = `{clinic_data.replace('`', "'").replace('${', '${'+'{')}`;
"""

with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Written to {OUT_PATH}")
