// Auto-generated by generate_clinic_data.py — do not edit manually
export const CLINIC_DATA = `NAME: Trevi, Jasmine Mother’s Recovery
WEBSITE: https://trevi.org.uk
ADDRESS: 29 Sutherland Road Plymouth PL4 6BW
REGION: Cornwall, England, Plymouth, South West, United Kingdom
PAYMENT: Local Authority, Private Pay
DETOX: True
GENDER: women_only
RATING: CQC - Good
THERAPIES: Yoga, Acupuncture, Trauma-Informed, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction
TYPE: Residential
ACCESSIBILITY: Women
SETTING: coastal
FAMILY_PROGRAMME: Yes
SUMMARY: If you're a mother struggling with addiction and want to recover while keeping your children with you, this Plymouth residential centre offers a rare, family-focused approach that understands the particular challenges you face. Run by the Trevi charity, it provides trauma-informed therapy alongside practical support to help you rebuild your relationship with your child while getting well. The programme includes counselling, group therapy, yoga and acupuncture in a safe, welcoming environment designed specifically for mothers and their families.

---

NAME: The Nehemiah Project
WEBSITE: https://www.tnp.org.uk/
ADDRESS: 47 Tooting Bec Gardens, Streatham, London, SW16 1RF
REGION: England, London, South London, United Kingdom
PAYMENT: Charity Funded
GENDER: men_only
THERAPIES: Cognitive Behavioural Therapy, Relapse Prevention
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: Men
SETTING: suburban
FAMILY_PROGRAMME: Yes
SUMMARY: This South London residential centre specialises in helping men recover from drug and alcohol addiction through a structured, abstinence-based programme that has supported people for over 20 years. The centre goes beyond treating addiction itself by also addressing the underlying issues that drive substance misuse, using therapies like cognitive behavioural therapy and relapse prevention. It's particularly suited to men looking for a focused, longer-term residential recovery programme with a proven track record in the local community.

---

NAME: ESH Community, Warwickshire
WEBSITE: https://www.eshcommunity.org/
ADDRESS: Warwickshire ESH Community, Southam, Warwickshire Esh Community, Holt Cottage Farm Welsh Road East Southam Warwickshire CV47 1NJ
REGION: Altrincham, Cheshire, Coventry, East Midlands, England, Gateshead, Herefordshire, Lincoln, North East, North West, Nottingham, Scarborough, Staffordshire, United Kingdom, Walsall, Warwick, West Midlands, Worcestershire
PAYMENT: Insurance, Local Authority, NHS, Payment Plans, Private Pay
DETOX: True
GENDER: mixed
MIN_AGE: 15
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Yoga, Meditation, Acupuncture, Relapse Prevention, Tai Chi, Group Therapy
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men
SETTING: rural
CAPACITY: 11 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: ESH Community is a well-established non-profit residential rehab in Warwickshire that treats alcohol and drug addiction alongside mental health conditions like ADHD, bipolar disorder and trauma. The centre combines professional therapy with peer support, offering a range of approaches including cognitive behavioural therapy, yoga, meditation and acupuncture, and can provide detoxification on site. It's a good fit for people who want compassionate, structured treatment in a supportive environment where they'll be understood by both staff and others in recovery.

---

NAME: Acquiesce Rehab
WEBSITE: https://acquiesce.org.uk/
ADDRESS: 25 All Saints Street, Bolton, BL12EJ
REGION: England, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
RATING: CQC - Outstanding
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Yoga, Acupuncture, Schema Therapy, Relapse Prevention, Hypnotherapy, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
CAPACITY: 12 beds
AFTERCARE: Yes
PRICING: om? Our residential treatment starts from £7,500. We tailor our packages to your needs, so call us today to ge
SUMMARY: This private residential centre in Bolton specialises in alcohol, drug, and behavioural addictions with a warm, person-centred approach that combines professional therapy with peer support to help you rebuild confidence and resilience. You'll benefit from a wide range of evidence-based treatments including cognitive behavioural therapy, mindfulness, yoga, and one-to-one counselling, available seven days a week even during evenings and bank holidays. Rated Outstanding by the Care Quality Commission, it's a good fit if you want comprehensive, compassionate care in a mixed residential setting.

---

NAME: The Priory Hospital Woking
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-woking/
ADDRESS: tent Home Clinics The Priory Hospital Woking The Priory Hospital Woking, Surrey Chobham Road, Knaphill, Woking, Surrey, GU21 2QF
REGION: England, Surrey, Sussex, United Kingdom, Worthing
PAYMENT: Insurance, NHS, Payment Plans, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
GENDER: mixed
FAITH: Christian
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, Eye Movement Desensitization, 12-Step, Mindfulness, Art Therapy, Yoga, Acupuncture, Relapse Prevention, Group Therapy
TREATS: Alcohol Addiction, Gambling Addiction, Internet & Social Media, Prescription Drug Addiction, Sex Addiction
ACCESSIBILITY: Men, Non English Speakers, Pregnant Women, Women
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This established private hospital in Surrey offers flexible inpatient, outpatient and day care programmes for adults struggling with addiction and mental health difficulties, with a strong focus on creating personalised treatment plans. The centre combines evidence-based therapies like CBT and DBT with complementary approaches such as yoga and art therapy, making it well-suited to those who want a comprehensive, rounded approach to recovery. As part of the respected Priory Group and rated Good by the Care Quality Commission, it provides the reassurance of professional oversight alongside a Christian ethos that some patients find supportive.

---

NAME: Passmores House, Essex
WEBSITE: https://www.viaorg.uk/services/passmores-house/
ADDRESS: Essex, England Skip to content Home Clinics Passmores House, Essex Passmores House, Harlow, Essex Third Avenue, Essex, CM18 6YL
REGION: Chelmsford, Crawley, East London, East of England, England, Essex, Guildford, Hertfordshire, High Wycombe, Ipswich, Kent, Maidstone, Margate, Norfolk, South East, Southend-on-Sea, Suffolk, Sussex, United Kingdom
PAYMENT: Private Pay
DETOX: True
GENDER: women_only
MIN_AGE: 18
RATING: CQC - Good Overall
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Acupuncture, Relapse Prevention, One-to-One Counselling
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Substances Addiction, Tramadol, Valium, Xanax
TYPE: Residential
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: suburban
SUMMARY: This women-only residential rehab centre in Harlow offers medically supervised detox and structured rehabilitation for alcohol and drug dependency, combining practical therapies like cognitive behavioural therapy, mindfulness and yoga with one-to-one support. It's run by Via, a UK charity with strong expertise in addiction treatment, and welcomes both NHS-funded referrals and private patients looking for integrated care. If you're a woman seeking a comprehensive programme that addresses both detoxification and longer-term recovery in one place, this centre provides that specialist combination of medical support and therapeutic treatment.

---

NAME: Francis House
WEBSITE: https://www.streetscene.org.uk/francis-house-southampton.html
ADDRESS: 2 Hulse Road, Southampton, Hampshire, SO15 2JX
REGION: Bournemouth, Brighton and Hove, Crawley, England, Guildford, Hampshire, Portsmouth, South East, South West, Southampton, Sussex, United Kingdom
COST: Budget-friendly Rehab
PAYMENT: Charity Funded, Local Authority, Private Pay
GENDER: mixed
FAITH: Spiritual (non-denominational)
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Internet & Social Media, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Substances Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: rural
CAPACITY: 18 beds
AFTERCARE: Yes
SUMMARY: This Southampton residential centre supports adults working towards abstinence from drugs, alcohol, and other substances through a mix of detox, talking therapies, and practical skills training in a small, mixed community of up to 18 people. It's particularly suited to those needing specialist help with trauma, bereavement, or relationship issues, as staff design individualised programmes to address your specific needs. The centre welcomes both self-funded clients and those referred through local authorities, offering an accessible route to recovery with therapies ranging from cognitive behavioural therapy to mindfulness and yoga.

---

NAME: Bayberry Manor
WEBSITE: https://bayberry.org.uk/premium-drug-rehab-alcohol-recovery/
ADDRESS: cs Bayberry Manor Bayberry Manor Residential Rehabilitation Centre Earlswood, Solihull Small Lane, Earlswood, Solihull, B94 5EL
REGION: Birmingham, Cheshire, Coventry, East Midlands, England, Herefordshire, Lincoln, Nottingham, Staffordshire, United Kingdom, Walsall, Warwick, Worcestershire
PAYMENT: Insurance, Private Pay
INSURANCE: Bupa
GENDER: mixed
FAITH: Christian
MIN_AGE: 18
RATING: CQC - Excellent
THERAPIES: Mindfulness, Trauma-Informed, Relapse Prevention, Gym, Swimming, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
AFTERCARE: Yes
SUMMARY: Bayberry Manor is a quiet countryside rehab centre in Solihull that treats alcohol and drug addiction alongside mental health and behavioural problems, combining medical expertise with a comfortable setting for genuine recovery. The centre is rated CQC Excellent and offers a mix of therapies including counselling, group sessions, mindfulness, and fitness activities, with staff who understand how trauma connects to addiction. It welcomes people from across the country and is rooted in Christian values, making it suitable for those seeking a discreet, supportive environment away from everyday pressures.

---

NAME: Wirral Residential Service (Phoenix Futures)
WEBSITE: https://www.phoenix-futures.org.uk/phoenix-futures-for/people-and-families-who-use-our-services/find-a-service/wirral-residential-service/
ADDRESS: sidential Service (Phoenix Futures) Wirral Residential Service (Phoenix Futures), Cheshire Upton Road, Bidston, Wirral, CH43 7QF
REGION: England, United Kingdom, Wirral
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Motivational Interviewing, Mindfulness, Relapse Prevention, Gym, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
CAPACITY: 35 beds
SUMMARY: This residential centre in Bidston offers structured recovery for adults dealing with drug, alcohol or substance misuse in a welcoming Edwardian setting with grounds and a community garden. The programme combines talking therapies like cognitive behavioural therapy and motivational interviewing with practical support including gym access, mindfulness and relapse prevention work. It's well suited to people wanting an immersive residential experience where they can live amongst others in recovery and benefit from both one-to-one counselling and group support.

---

NAME: Nelson Trust, East Wharf Cottage
WEBSITE: https://www.nelsontrust.com/
ADDRESS: 1 Brunswick Square, Gloucester, GL1 1UG
REGION: Bangor, Bristol, Cardiff, Cirencester, England, Gloucester, Newport, Oxfordshire, Reading, Shropshire, Swansea, United Kingdom, Wrexham
PAYMENT: Local Authority, Private Pay
GENDER: women_only
MIN_AGE: 40
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, Eye Movement Desensitization, Art Therapy, Yoga, Acupuncture, Trauma-Informed, Psychoeducation, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Pregnant Women, Women
SETTING: suburban
CAPACITY: 44 beds
FAMILY_PROGRAMME: Yes
SUMMARY: This women-only residential centre offers compassionate support for people dealing with drug or alcohol problems alongside other challenges like trauma, domestic abuse or involvement with the courts. The team uses a range of therapies including talking treatments, yoga and acupuncture within a trauma-informed approach that recognises how past experiences affect recovery. As a well-established charity, they work with thousands of people each year and are rated Good by the CQC, making them particularly suited to women who need specialised, holistic care addressing the root causes of their addiction.

---

NAME: Ark House
WEBSITE: https://arkhouserehab.co.uk/
ADDRESS: 15 Valley Road, Scarborough, North Yorkshire, YO11 2LY
REGION: England, North East, United Kingdom, York
PAYMENT: Private Pay
DETOX: True
GENDER: mixed
MIN_AGE: 30
RATING: CQC - Outstanding
THERAPIES: 12-Step, Mindfulness, Yoga, Acupuncture, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: coastal
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This long-established centre in Scarborough has been helping people recover from alcohol, drugs, and behavioural addictions for over 30 years, using a personalised 12-Step approach combined with therapies like counselling, mindfulness, and yoga. It's a good fit if you want a fully residential programme with detoxification on site, flexible pricing, and access to both one-to-one support and group therapy in a welcoming, mixed-gender environment. The centre is rated Outstanding by the Care Quality Commission and welcomes people from across Yorkshire and beyond.

---

NAME: Kenward House (Kenward Trust)
WEBSITE: https://www.kenwardtrust.org.uk/
ADDRESS: to content Home Clinics Kenward House (Kenward Trust) Kenward House (Kenward Trust), Kent Kenward Road, Yalding, Kent, ME18 6AH
REGION: Canterbury, Crawley, England, Guildford, Kent, Margate, Norfolk, Sandwich, South East, Southend-on-Sea, Suffolk, Sussex, Ticehurst, United Kingdom
PAYMENT: Charity Funded, Private Pay
GENDER: mixed
FAITH: Christian
MIN_AGE: 50
RATING: CQC - Good
THERAPIES: 12-Step, Art Therapy, Yoga, Reiki, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
CAPACITY: 20 beds
FAMILY_PROGRAMME: Yes
PRICING: our rehabilitation centre is £1900 per week for 6 weeks. Programme length is tailored to individual needs, an
SUMMARY: This established Kent centre has been helping people recover from drug and alcohol addiction for over 50 years, bringing real expertise to personalised treatment that combines talking therapies with complementary approaches like yoga and acupuncture. It's a welcoming, mixed-gender environment grounded in Christian values that suits both NHS-referred patients and self-funding clients looking for warm, practical support. The centre is regulated with a Good CQC rating and works closely with local services to give you the best chance of lasting recovery.

---

NAME: Druglink (Oxygen Recovery)
WEBSITE: https://www.oxygenrecovery.co.uk/
ADDRESS: overy) Residential Treatment Hemel Hempstead, Hertfordshire Nascent House, London Road, Hemel Hempstead, Hertfordshire, HP3 9ST
REGION: England, Hemel Hempstead, United Kingdom
DETOX: True
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Motivational Interviewing, Mindfulness, Art Therapy, Yoga, Acupuncture, Auricular Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
AFTERCARE: Yes
SUMMARY: This Hemel Hempstead residential centre, run by the charity Druglink, supports people struggling with drug, alcohol or behavioural addictions through a blend of clinical treatment and community-based care. It suits those who want a structured programme combining therapies like cognitive behavioural therapy, mindfulness and art therapy with practical skills like relapse prevention and group support. The centre can handle detoxification on site and tailors its costs to your individual needs and how long you stay, making it accessible for different circumstances.

---

NAME: Western Counselling
WEBSITE: https://www.westerncounselling.com/
ADDRESS: 3 Ellenborough Park Road, Weston-super-Mare, North Somerset, BS23 1XJ
REGION: England, United Kingdom, Weston-super-Mare
PAYMENT: Private Pay
GENDER: mixed
MIN_AGE: 35
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Yoga, Reiki, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
AFTERCARE: Yes
SUMMARY: This long-established centre in Weston-super-Mare has been helping people recover from alcohol, drugs, gambling and co-dependency since 1983, combining the proven 12-step approach with modern therapies like CBT, mindfulness and yoga. What sets it apart is its focus on treating not just the addiction itself but also the underlying issues driving it, supported by regular one-to-one counselling and group work. It's a good fit if you're looking for a residential programme that takes a thorough, well-rounded approach to your recovery.

---

NAME: Nelson House
WEBSITE: https://www.nelsontrust.com
ADDRESS: content Home Clinics Nelson House Nelson House (The Nelson Trust), Gloucestershire Brimscombe Hill, Brimscombe, Stroud, GL5 2QP
REGION: England, United Kingdom
PAYMENT: Charity Funded
GENDER: mixed
MIN_AGE: 30
RATING: CQC - Requires Improvement
THERAPIES: Mindfulness, Yoga, Acupuncture, Trauma-Informed, Relapse Prevention, Group Therapy, Individual Counselling
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
CAPACITY: 25 beds
FAMILY_PROGRAMME: Yes
SUMMARY: This mixed-gender residential centre in Gloucestershire offers structured addiction treatment for alcohol and drug misuse using a trauma-informed approach that recognises how past experiences affect recovery. The programme combines talking therapies with practical skills like mindfulness, yoga and relapse prevention to help you rebuild your life. Costs are flexible and tailored to your individual needs and how long you need to stay.

---

NAME: Harper House (Phoenix Futures)
WEBSITE: https://www.phoenix-futures.org.uk/phoenix-futures-for/people-and-families-who-use-our-services/find-a-service/harper-house/
ADDRESS: 92 Canal Street, Saltcoats, KA21 5JB
REGION: East Kilbride, Glasgow, Hamilton, Kilmarnock, Paisley, Scotland, Stirling, United Kingdom
PAYMENT: Local Authority
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Meditation, Acupuncture, Family Therapy, Relapse Prevention, Swimming, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: coastal
CAPACITY: 20 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This specialist rehab centre in Saltcoats puts family involvement at the heart of recovery, helping adults tackle drug and alcohol misuse through a mix of talking therapies, mindfulness, yoga and practical support like relapse prevention. The team works closely with the NHS to create personalised treatment plans, and you'll have access to counselling both one-to-one and in groups, alongside complementary therapies designed to support your wellbeing. It's a good choice if you want your loved ones involved in your recovery journey and prefer a holistic approach that treats the whole person, not just the addiction.

---

NAME: Bayberry Meadows
WEBSITE: https://bayberry.org.uk/oxfordshire-drug-rehab-alcohol-recovery/
REGION: Altrincham, Birmingham, Cheshire, Coventry, Derbyshire, East Midlands, England, Herefordshire, Lincoln, Nottingham, Staffordshire, United Kingdom, Walsall, Warwick, West Midlands, Worcestershire
PAYMENT: Insurance, Private Pay
INSURANCE: Bupa
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Excellent
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Trauma-Informed, Group Therapy
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
AFTERCARE: Yes
SUMMARY: This small, peaceful rehab centre near Solihull welcomes just six residents at a time, making it ideal if you value privacy and personalised attention during your recovery from alcohol or drug addiction. Set in beautiful countryside with gardens and meadows, it combines proven therapies like cognitive behavioural therapy and mindfulness with a compassionate, person-centred approach to help you rebuild your life. The centre holds an excellent CQC rating and suits anyone seeking a discreet, intimate environment away from busy settings.

---

NAME: Gloucester House
WEBSITE: https://www.salvationarmy.org.uk/gloucester-house/
ADDRESS: 6 High Street, Highworth Swindon SN6 7AG
REGION: Bristol, Chelmsford, Cheltenham, England, Gloucester, Guildford, High Wycombe, Oxford, South West, Surrey, Swindon, United Kingdom, Woking
PAYMENT: Charity Funded, Local Authority, Payment Plans, Private Pay
GENDER: men_only
FAITH: Christian
MIN_AGE: 60
RATING: CQC - Good
THERAPIES: 12-Step, Yoga, Acupuncture, Relapse Prevention, Occupational Therapy, Gym, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men
SETTING: rural
CAPACITY: 4 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This men-only centre in Highworth, Swindon has been supporting people with alcohol, drug, and behavioural addictions since 1960, offering a two-stage approach that moves from intensive treatment to gradually preparing you for independent living. Run by The Salvation Army with a Christian foundation, it combines proven therapies like counselling, group work, and 12-Step programmes with practical activities including yoga, acupuncture, and gym sessions to support your whole recovery. It's a good choice if you're a man looking for a well-established, structured programme that takes you step by step from crisis to rebuilding a meaningful life.

---

NAME: The Wellbourne Clinic
WEBSITE: https://thewellbourneclinic.co.uk/
ADDRESS: 43 Waverley Road, Kenilworth, CV8 1JL
REGION: Birmingham, England, Herefordshire, United Kingdom, Warwick, West Midlands
DETOX: True
GENDER: mixed
MIN_AGE: 18
THERAPIES: Cognitive Behavioural Therapy, Yoga, Meditation, Acupuncture, Schema Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
AFTERCARE: Yes
SUMMARY: This residential rehab in Kenilworth combines clinical care with holistic therapies like yoga, meditation and acupuncture to help adults overcome addiction to alcohol, drugs or prescription medication. What sets it apart is the intimate setting with just six residents at a time, creating a calm and supportive atmosphere where you can focus on your recovery without feeling overwhelmed. If you're looking for personalised treatment that blends traditional therapy with complementary approaches, this clinic offers on-site detox and a range of talking therapies tailored to your needs.

---

NAME: The BAC O’Connor Centre
WEBSITE: https://www.bacandoconnor.co.uk/
ADDRESS: 126 Station St, Burton-on-Trent DE14 1BX
REGION: Birmingham, Bristol, Burton upon Trent, Cheltenham, Cheshire, Coventry, Derbyshire, England, Herefordshire, Lancaster, North West, Shropshire, Somerset, South West, Staffordshire, Stoke-on-Trent, United Kingdom, Walsall, Warwick, West Midlands, Wolverhampton, Worcestershire
PAYMENT: Local Authority, Private Pay
DETOX: True
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Prescription Drug Addiction
ACCESSIBILITY: Men, Women
SETTING: suburban
CAPACITY: 36 beds
FAMILY_PROGRAMME: Yes
SUMMARY: This Burton-on-Trent centre has been helping people recover from drug and alcohol addiction since 1998, using a mix of talking therapies like CBT and DBT alongside complementary approaches such as yoga and acupuncture. The service is built on a therapeutic community model where you'll work through a personalised programme designed for lasting recovery, with both one-to-one support and group work available. It's a welcoming place for anyone ready to make a real change, and you can go through detox and rehabilitation all in one setting.

---

NAME: T.H.O.M.A.S Women’s Rehab
WEBSITE: https://thomasonline.org.uk/
REGION: England, United Kingdom
PAYMENT: Charity Funded
GENDER: women_only
THERAPIES: Cognitive Behavioural Therapy, Motivational Interviewing, 12-Step, Yoga, Acupuncture, Trauma-Informed, Group Therapy
TREATS: Alcohol Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Women
SETTING: suburban
SUMMARY: This specialist centre in Greater Manchester offers residential treatment designed specifically for women recovering from drug and alcohol addiction, providing a safe, trauma-informed environment where you can rebuild confidence and stability. The team uses a range of therapies including cognitive behavioural therapy, motivational interviewing, yoga, and acupuncture to support your recovery. It's an ideal choice if you're a woman seeking compassionate, person-centred care that understands the particular challenges women face in addiction recovery.

---

NAME: Oxygen Detox (Druglink)
WEBSITE: https://www.druglink.co.uk/oxygen-detox/
ADDRESS: to content Home Clinics Oxygen Detox (Druglink) Oxygen Detox (Druglink), Hertfordshire Trefoil House, Hemel Hempstead, HP3 9TE
REGION: Hemel Hempstead, London, United Kingdom
GENDER: mixed
RATING: CQC - Good
THERAPIES: Mindfulness, Art Therapy, Yoga, Acupuncture, Auricular Acupuncture, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Women
SUMMARY: This specialist medical detox centre in Hertfordshire helps people safely withdraw from drugs or alcohol under medical supervision, combining practical support with therapies like counselling, yoga, mindfulness and art therapy to address both the physical and emotional sides of addiction. It's run by the charity Druglink and works best for anyone needing a structured, short-term programme to make those crucial first steps towards recovery in a compassionate environment. The centre is rated Good by the CQC and welcomes both men and women.

---

NAME: Turning Point Leigh Bank
WEBSITE: https://www.turning-point.co.uk/services/leigh-bank-rehabilitation-service
ADDRESS: 16 Edward St, Oldham OL9 7QW
REGION: England, Manchester, United Kingdom
PAYMENT: Insurance, Local Authority, NHS, Private Pay
DETOX: True
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Meditation, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: suburban
CAPACITY: 16 beds
FAMILY_PROGRAMME: Yes
SUMMARY: This Oldham-based residential centre offers structured rehabilitation for adults struggling with drug and alcohol misuse, combining talking therapies like cognitive behavioural therapy with complementary approaches such as yoga, mindfulness and acupuncture. The team go beyond treating addiction itself to help you rebuild your life and develop practical skills for staying well, drawing on real experience of what recovery involves. It's a mixed-gender facility rated Good by the Care Quality Commission, with detoxification support available on site.

---

NAME: Addiction Recovery Centre (ARC)
WEBSITE: https://arcproject.org.uk/
ADDRESS: 54 Northern Rd, Cosham, Portsmouth PO6 3DP
REGION: England, Portsmouth, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
RATING: CQC - Requires Improvement
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Meditation, Acupuncture, Psychoeducation, Relapse Prevention, Transactional Analysis, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SUMMARY: This Portsmouth residential centre offers an abstinence-based programme combining talking therapies like cognitive behavioural therapy with holistic approaches including mindfulness, yoga and acupuncture, along with group and one-to-one support. New residents start in their dedicated Welcome House where they receive intensive counselling and group therapy before moving into the main programme. It suits people looking for a mixed-gender facility that blends professional psychological treatment with wellness practices to support long-term recovery from alcohol and drug misuse.

---

NAME: T.H.O.M.A.S Mens
WEBSITE: https://thomasonline.org.uk/
ADDRESS: nt Home Clinics T.H.O.M.A.S Mens T.H.O.M.A.S. Men's Witton Bank, Blackburn Witton Bank Spring Lane Blackburn Lancashire BB2 2PW
REGION: England, Manchester, Salford, United Kingdom
COST: Budget-friendly Rehab
PAYMENT: Charity Funded, Insurance, Local Authority, NHS
GENDER: men_only
MIN_AGE: 30
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Yoga, Acupuncture, Gym, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
TYPE: Residential
ACCESSIBILITY: Men
SETTING: suburban
SUMMARY: This men-only centre in Blackburn offers a warm, structured environment where men can recover from drug and alcohol addiction with the support of a charity that has spent over 30 years helping people rebuild their lives. You'll find a good mix of talking therapies like counselling and group work alongside practical activities such as yoga, gym sessions and mindfulness to support your recovery. It's a particularly good fit if you're looking for affordable treatment in a community-focused setting where you won't feel judged.

---

NAME: Bosence Farm
WEBSITE: https://www.bosencefarm.com/
ADDRESS: 69 Bosence Road, Townshend, Hayle, Cornwall, TR27 6AN
REGION: Cornwall, England, United Kingdom
PAYMENT: Charity Funded, Insurance, Local Authority, NHS, Private Pay
DETOX: True
GENDER: mixed
RATING: CQC - Good
THERAPIES: Mindfulness, Yoga, Acupuncture, Family Therapy, Trauma-Informed, Relapse Prevention, Tai Chi, Gym, Group Therapy
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Non English Speakers, Pregnant Women, Teenagers (16-18), Women
CAPACITY: 21 beds
SUMMARY: This established Cornwall-based rehab centre combines medical detoxification with holistic therapies like mindfulness, yoga and acupuncture in peaceful, welcoming surroundings. It's well suited to people wanting a blend of clinical care and natural healing practices, with both private and NHS-funded places available. The two-week detox programme is followed by longer-term residential treatment to help you rebuild your life away from everyday pressures.

---

NAME: Mount Carmel
WEBSITE: https://www.mountcarmel.org.uk/
ADDRESS: 12 Aldrington Road, London, SW16 1TH
REGION: England, London, South London, United Kingdom
PAYMENT: Private Pay
GENDER: men_only
MIN_AGE: 40
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Equine-Assisted, Yoga, Meditation, Acupuncture, Auricular Acupuncture, Massage, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: suburban
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This South London centre has over 40 years of experience helping men recover from alcohol addiction through a wide range of therapies, from talking treatments and the 12-Step programme to yoga, acupuncture and equine-assisted therapy. As a not-for-profit organisation, it offers affordable treatment whether you're referred through the NHS or paying privately. It's a good fit if you're looking for a specialist alcohol rehab with a supportive, holistic approach and a team committed to helping you stay sober long-term.

---

NAME: Somewhere House
WEBSITE: https://www.somewherehouse.com/
ADDRESS: 68 Berrow Rd, Burnham-on-Sea, TA8 2EZ
REGION: Burnham-on-Sea, England, Somerset, United Kingdom
PAYMENT: Private Pay
DETOX: True
GENDER: mixed
RATING: CQC - Good
THERAPIES: Equine Therapy, Family Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: coastal
CAPACITY: 7 beds
AFTERCARE: Yes
SUMMARY: This Somerset rehab centre takes a thorough approach to recovery by treating both addiction and the mental health issues underneath, such as trauma, PTSD, and eating disorders. You'll benefit from a range of therapies including equine therapy, family sessions, and one-to-one counselling, all delivered in a structured, person-centred way. If you need somewhere supportive to live after treatment, they also offer move-on housing for people committed to staying abstinent.

---

NAME: The Recovery Lodge
WEBSITE: https://www.therecoverylodge.co.uk/
ADDRESS: 23 The Street, Bapchild, Sittingbourne, Kent, ME9 9AD
REGION: Crawley, England, Guildford, High Wycombe, Kent, Sandwich, Sittingbourne, Sussex, United Kingdom
PAYMENT: Insurance, Private Pay
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: suburban
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This Kent-based residential centre offers structured, person-centred treatment for drug and alcohol addiction, treating both the physical withdrawal and the deeper psychological issues that drive substance use. The team combines therapies like cognitive behavioural therapy, counselling, yoga and acupuncture to support long-term recovery in a safe, confidential setting. It's well suited to anyone ready to commit to residential treatment and wanting professional support through both detoxification and the emotional work of lasting change.

---

NAME: Streetscene Cornerways
WEBSITE: https://www.streetscene.org.uk/cornerways-bournemouth.html
ADDRESS: 20 Braidley Road, Bournemouth, England, BH2 6JX
REGION: Bournemouth, England, Plymouth, South West, Southampton, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
FAITH: Christian
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Yoga, Acupuncture, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction
ACCESSIBILITY: Men, Pregnant Women, Women
SETTING: rural
CAPACITY: 20 beds
AFTERCARE: Yes
SUMMARY: This Bournemouth residential centre offers warm, professional support for adults struggling with alcohol or drug dependency who need round-the-clock care to recover. The team combines talking therapies like cognitive behavioural therapy and counselling with holistic approaches such as yoga, acupuncture and art therapy, alongside practical help with life planning. It's a good fit if you're looking for a Christian-informed environment that treats you as a whole person rather than just addressing addiction in isolation.

---

NAME: The Grange (Priory Life Works)
WEBSITE: https://www.lifeworkscommunity.com/
ADDRESS: Clinics The Grange (Priory Life Works) The Grange (Priory Life Works), Woking, Surrey High Street, Old Woking, Surrey, GU22 8LB
REGION: England, Surrey, United Kingdom, Woking
PAYMENT: Insurance, Private Pay
GENDER: mixed
RATING: CQC - Good
THERAPIES: 12-Step, Mindfulness, Yoga, Acupuncture, Family Therapy, Relapse Prevention, Individual Counselling
TREATS: Alcohol Addiction, Amphetamine, Behavioural Addiction, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Gambling Addiction, Heroin, Internet & Social Media, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Tramadol, Valium, Video Game Addiction, Xanax
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
PRICING: or a 14-day stay, equating to £495 per night Call 0330 056 6041 Call Us Tap on a number to call Treatment enqu
SUMMARY: This welcoming residential centre in Surrey offers comprehensive support for alcohol and drug addiction alongside behavioural issues like gaming and gambling, drawing on over twenty years of experience within the trusted Priory Group. The team use a blend of talking therapies, mindfulness, yoga and acupuncture to help you recover, with free same-day assessments available so you can start treatment straight away. It's a good choice if you're looking for a mixed-gender environment with practical support for relapse prevention and family involvement in your recovery journey.

---

NAME: Kendrick Mews (PROMIS)
WEBSITE: https://www.promis.co.uk/
ADDRESS: 12 Kendrick Mews, South Kensington, England, SW7 3HG
REGION: Central London, East London, England, London, North London, South London, United Kingdom, West London
PAYMENT: Private Pay
GENDER: men_only
MIN_AGE: 35
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Acupuncture, Gym
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: rural
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This small, men-only residential centre in South Kensington offers discreet and personalised addiction treatment with just nine private bedrooms, making it ideal if you value privacy and individual attention. The team combines therapies like cognitive behavioural therapy, mindfulness, yoga and acupuncture to support recovery from substance misuse alongside any mental health or trauma concerns. It's a good fit if you want intensive, focused care in a calm London setting where the emphasis is on building resilience and a balanced life rather than abstinence alone.

---

NAME: The Haynes Clinic
WEBSITE: https://thehaynesclinic.com/
ADDRESS: 7 Warren Court, Chicksands, Shefford, Bedfordshire, SG17 5QB
REGION: Bedford, Crawley, Derby, East Midlands, England, Guildford, Hemel Hempstead, High Wycombe, Leicester, Lincoln, Luton, Milton Keynes, Norfolk, Northampton, Nottingham, Peterborough, South East, Suffolk, Sussex, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Yoga, Acupuncture, Relapse Prevention, Anger Management, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Amphetamine, Behavioural Addiction, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Gambling Addiction, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: rural
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: Set in peaceful Bedfordshire countryside, The Haynes Clinic offers private residential treatment for alcohol, drugs, prescription medication, and behavioural addictions like gambling in a calm and discreet environment. The clinic combines established approaches including cognitive behavioural therapy, 12-step work, yoga, and acupuncture, with a focus on building lasting recovery rather than quick fixes. It's particularly well-suited to people who value a quieter setting away from daily pressures and want comprehensive support tailored to their individual needs.

---

NAME: Shardale Rehab
WEBSITE: https://www.shardalerehab.co.uk/
ADDRESS: 385 Clifton Drive North, Lytham, Lancashire, FY8 2NW
REGION: England, Lancashire, Rotherham, United Kingdom
GENDER: mixed
RATING: CQC - Requires Improvement
THERAPIES: Relapse Prevention, Group Therapy, One-to-One Counselling
CAPACITY: 36 beds
SUMMARY: This 36-bed residential centre in Lytham St Annes uses a therapeutic community approach, meaning you'll get support from both qualified staff and other people in recovery, which builds genuine friendships alongside your treatment. Through group therapy, one-to-one counselling, and relapse prevention workshops, you'll develop practical skills to understand your addiction and rebuild a stable life. It's a good fit if you're looking for a mixed-gender environment where peer support and professional care work together to help you recover from drug or alcohol dependence.

---

NAME: The Priory Hospital Roehampton
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-roehampton-london/
ADDRESS: ent Home Clinics The Priory Hospital Roehampton The Priory Hospital Roehampton, Wandsworth, London Priory Lane, London, SW15 5JJ
REGION: East of England, England, Hertfordshire, London, Swindon, United Kingdom
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
DETOX: True
GENDER: men_only
RATING: CQC - Good
THERAPIES: 12-Step, Mindfulness, Yoga, Family Therapy, Group Therapy, One-to-One Counselling
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This well-established London hospital offers comprehensive addiction and mental health treatment for men in a distinctive setting of historic buildings and peaceful grounds. With over 140 years of experience, it combines traditional therapies like the 12-Step programme with more contemporary approaches such as mindfulness and yoga, alongside tailored counselling and family support. The centre is particularly suited to those seeking inpatient care in a calm, therapeutic environment where they can access on-site detoxification and recovery support.

---

NAME: The Bridges Hull
WEBSITE: http://thebridges.org.uk/
ADDRESS: 335 Beverley Road, Hull, HU5 1LD
REGION: England, Hull, Scarborough, United Kingdom, Yorkshire and the Humber
PAYMENT: Charity Funded, Local Authority
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Requires Improvement
THERAPIES: 12-Step, Mindfulness, Yoga, Meditation, Acupuncture, Relapse Prevention, Gym, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: suburban
FAMILY_PROGRAMME: Yes
SUMMARY: This East Yorkshire residential centre has been supporting people through addiction recovery for nearly two decades, offering tailored treatment programmes that combine therapy with practical life skills to help you stay on track long term. You'll find a welcoming mixed-gender environment with a range of approaches including counselling, group therapy, mindfulness and yoga to suit different needs. The Bridges Hull is particularly suited to anyone wanting structured, personalised support to break free from drugs or alcohol and rebuild a stable life.

---

NAME: Turning Point – Smithfield Detoxification Unit
WEBSITE: https://www.turning-point.co.uk/
ADDRESS: t Budget-friendly Rehab Turning Point - Smithfield Detoxification Unit Thompson Street, Collyhurst, Greater Manchester, M4 5FY
REGION: England, United Kingdom
PAYMENT: Local Authority, Private Pay
DETOX: True
GENDER: mixed
MIN_AGE: 60
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Yoga, Acupuncture, Relapse Prevention, Group Therapy
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Ketamine, Morphine, Opioid, Oxycontin, Prescription Drug Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: Men, Women
SETTING: suburban
CAPACITY: 22 beds
SUMMARY: This specialist detox and rehab centre in Manchester offers medically managed treatment for adults struggling with drug and alcohol addiction, with a range of therapies including cognitive behavioural therapy, mindfulness, yoga and relapse prevention to support your recovery. The 22-bed unit provides intensive inpatient care tailored to your needs, and has been trusted by the Care Quality Commission since 2011. It works closely with local community drug and alcohol teams, making it a good choice if you need structured, evidence-based detoxification with ongoing therapeutic support.

---

NAME: The Priory Hospital Altrincham
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-altrincham-manchester/
ADDRESS: ent Home Clinics The Priory Hospital Altrincham The Priory Hospital Altrincham, Manchester Rappax Road, Hale, Cheshire, WA15 0NX
REGION: Altrincham, Blackpool, Bolton, Bradford, Cheshire, Coventry, England, Lancashire, Liverpool, Manchester, North West, Oldham, Salford, Staffordshire, Stockport, Stoke-on-Trent, United Kingdom, Walsall, Warrington, Warwick, West Midlands, Wigan, Wirral, Wolverhampton, Worcestershire
PAYMENT: Insurance, NHS, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
DETOX: True
GENDER: men_only
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Family Therapy, Psychoeducation, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This men-only residential centre in Greater Manchester offers specialist addiction treatment alongside mental health support, making it particularly suitable for those needing to address both issues together. The hospital provides a range of evidence-based therapies including cognitive behavioural therapy, family therapy and mindfulness, delivered through both one-to-one counselling and group sessions. It's a CQC-regulated facility that can manage detoxification on site and welcomes both NHS and private clients.

---

NAME: The Priory Hospital Glasgow
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-glasgow/
ADDRESS: 40 Mansionhouse Road, Langside, Renfrewshire, G41 3DW
REGION: East Kilbride, Erskine, Glasgow, Hamilton, Kilmarnock, Livingston, Paisley, Scotland, Stirling, United Kingdom
PAYMENT: Insurance, Local Authority, NHS, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
DETOX: True
GENDER: men_only
RATING: Healthcare Improvement Scotland - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, 12-Step, Mindfulness, Psychoeducation, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: city
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This men-only private hospital in Glasgow's west end offers residential treatment for alcohol and drug addiction alongside mental health conditions like depression, anxiety and eating disorders. It combines specialist expertise with a range of talking therapies including cognitive behavioural therapy, mindfulness and one-to-one counselling, along with on-site detoxification if needed. It's a good choice if you're looking for a regulated facility that treats both addiction and underlying mental health issues in a dedicated male environment.

---

NAME: Adferiad Parkland Place
WEBSITE: http://www.parklandplace.co.uk/
ADDRESS: 100 Llanelian Road, , Conwy, LL29 9UH
REGION: Bangor, Colwyn Bay, United Kingdom, Wales, Wrexham
PAYMENT: Charity Funded, Local Authority, Private Pay
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, SMART Recovery, Yoga, Acupuncture, Psychoeducation, Relapse Prevention, Anger Management, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: Men, Pregnant Women, Women
SETTING: rural
CAPACITY: 16 beds
SUMMARY: This CIW-registered rehab centre in North Wales offers tailored recovery programmes for alcohol, drugs, gambling and behavioural addictions, backed by a charity with over 50 years of experience supporting people with addiction and mental health challenges. The centre stands out for its specialist gambling addiction programme, fully funded by GambleAware, alongside a full range of therapies including counselling, cognitive behavioural therapy, yoga and acupuncture. It's a good fit if you're looking for a personalised approach to recovery in a welcoming residential setting that combines professional expertise with therapeutic variety.

---

NAME: The Priory Hospital Ticehurst House
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-ticehurst-house/
ADDRESS: riory Hospital Ticehurst House The Priory Hospital Ticehurst House, Wadhurst, East Sussex Ticehurst House, East Sussex, TN5 7HU
REGION: England, Sussex, Ticehurst, United Kingdom, Worthing
PAYMENT: NHS, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, 12-Step, Trauma-Informed, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This peaceful East Sussex retreat offers private residential treatment for drug and alcohol addiction alongside mental health support, set within a beautiful Grade I listed building surrounded by countryside grounds. The programme combines evidence-based therapies like CBT and trauma-informed care with a luxury setting and high-quality accommodation, making it ideal if you're seeking a discreet, comfortable space to focus on recovery. It's rated Good by the CQC and suits those wanting personalised treatment delivered in an upmarket environment.

---

NAME: Phoenix Futures’ National Specialist Family Service
WEBSITE: https://www.phoenix-futures.org.uk/phoenix-futures-for/people-and-families-who-use-our-services/find-a-service/specialist-family-service-england-and-wales/
ADDRESS: 31 Collegiate Crescent, South Yorkshire, S10 2BJ
REGION: Bolton, Bradford, Doncaster, England, Hull, Leeds, Manchester, North East, North West, Oldham, Rotherham, Salford, Scarborough, Sheffield, Stockport, United Kingdom, Warrington, Wigan, York
PAYMENT: Charity Funded, Local Authority
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Group Therapy
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
ACCESSIBILITY: Men, Pregnant Women, Women
SETTING: coastal
SUMMARY: This Sheffield-based residential centre is specially designed for parents seeking addiction treatment while keeping their children with them, combining structured rehab with on-site childcare and parenting support. It's ideal if you're looking to recover from drug or alcohol dependency without being separated from your family during treatment. The centre uses evidence-based therapies including cognitive behavioural therapy and group work to support both your recovery and your role as a parent.

---

NAME: The Priory Hospital North London
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-north-london/
ADDRESS: nt Home Clinics The Priory Hospital North London The Priory Hospital North London Grovelands House, The Bourne, London, N14 6RA
REGION: East of England, England, Hemel Hempstead, Hertfordshire, London, North London, United Kingdom, West London
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
GENDER: mixed
RATING: CQC - Good
THERAPIES: Trauma-Informed, Group Therapy, One-to-One Counselling
SETTING: suburban
CAPACITY: 85 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This Southgate-based hospital treats both adults and young people struggling with mental health issues like depression and anxiety, as well as addiction, using trauma-informed therapy and one-to-one counselling. You can choose between inpatient stays, day-care visits, or outpatient appointments depending on what suits your situation best. It's a good choice if you want specialist addiction support combined with broader mental health care in a flexible setting.

---

NAME: The Priory Hospital Bristol
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-bristol/
ADDRESS: Home Clinics The Priory Hospital Bristol The Priory Hospital Bristol, Stapleton Heath House Lane, Stapleton, Somerset, BS16 1EQ
REGION: Burnham-on-Sea, England, Somerset, United Kingdom, Weston-super-Mare
PAYMENT: Charity Funded, Local Authority, NHS
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, 12-Step, Mindfulness, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction
ACCESSIBILITY: Men, Women
SETTING: rural
CAPACITY: 85 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This private hospital in Somerset offers specialist care for addiction alongside mental health conditions, making it ideal if you're struggling with both substance use and related emotional or psychological issues. The centre combines evidence-based therapies like cognitive behavioural therapy with holistic approaches including yoga and mindfulness, so you can choose treatments that suit your personal recovery style. As part of the established Priory Group and rated as Good by the Care Quality Commission, it provides the reassurance of a regulated, well-respected service with experienced staff.

---

NAME: Clouds House
WEBSITE: https://forwardtrust.org.uk/service/clouds-house
ADDRESS: ds House Clouds House Action On Addiction Treatment Facility Wiltshire, Salisbury Clouds House, East Knoyle, Wiltshire, SP3 6BE
REGION: England, United Kingdom
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Relapse Prevention, Group Therapy, One-to-One Counselling
SETTING: rural
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This established charity-run centre in rural Wiltshire has been supporting adults with alcohol and drug dependency since 1983, offering a calm setting away from everyday pressures where you can focus on recovery. They provide practical therapies including one-to-one counselling, group support, and relapse prevention, and can accept you through the NHS, local authorities, or privately. It's a good choice if you're looking for a respected, long-established programme with a track record of helping people take that crucial first step towards lasting change.

---

NAME: Hay Farm (PROMIS)
WEBSITE: https://www.promis.co.uk/
ADDRESS: Pricing – Ham, Kent Skip to content Home Clinics Hay Farm (PROMIS) Hay Farm Clinic (PROMIS), Kent Hay Lane, Ham, Kent, CT14 0EE
REGION: Canterbury, Crawley, East London, East of England, England, Guildford, Hertfordshire, Kent, Margate, Norfolk, Norwich, Sandwich, Sittingbourne, South East, Suffolk, Surrey, Sussex, Ticehurst, United Kingdom
PAYMENT: Insurance, Private Pay
GENDER: mixed
MIN_AGE: 30
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, Eye Movement Desensitization, Motivational Interviewing, 12-Step, SMART Recovery, Mindfulness, Equine Therapy, Yoga, Acupuncture, Gym, Group Therapy
TREATS: Alcohol Addiction, Amphetamine, Behavioural Addiction, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Gambling Addiction, Heroin, Internet & Social Media, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Tramadol, Valium, Video Game Addiction, Xanax
ACCESSIBILITY: LGBTQ+ Friendly, Men, Women
SETTING: rural
CAPACITY: 14 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This 14-bed residential clinic in rural Kent specialises in treating addiction, mental health conditions, eating disorders and trauma in a peaceful farmland setting that encourages genuine healing and reflection. The centre offers a wide range of evidence-based therapies including cognitive behavioural therapy, dialectical behaviour therapy and equine therapy, alongside yoga, mindfulness and acupuncture to support your recovery. It is best suited to anyone seeking comprehensive, individualised treatment in a calm countryside environment away from everyday pressures.

---

NAME: Sefton Park Rehab, Somerset
WEBSITE: https://www.seftonparkrehab.co.uk
ADDRESS: 10 Royal Crescent , Somerset, BS23 2AX
REGION: Bristol, Cardiff, Cheltenham, Cornwall, England, Exeter, Newport, Slough, South West, Swansea, United Kingdom, Weston-super-Mare, Wrexham
COST: Standard Rehab
PAYMENT: Charity Funded, Insurance, Local Authority, NHS, Private Pay
GENDER: mixed
RATING: CQC - Outstanding
THERAPIES: Cognitive Behavioural Therapy, Yoga, Acupuncture, Family Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
TYPE: Residential
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: coastal
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This seafront rehab centre in Somerset combines professional addiction treatment with genuine care for your mental health, all within a welcoming Grade II listed building that feels more like a home than a clinical facility. You'll benefit from a range of therapies including counselling, cognitive behavioural therapy, family sessions and relapse prevention, tailored to help you recover from alcohol, drugs or other substance use. It's particularly suited to adults who want compassionate, personalised support in a calm seaside setting, with the added reassurance of an Outstanding CQC rating.

---

NAME: TLC Rehab, London
WEBSITE: https://tlcrehab.co.uk/
ADDRESS: 81 Torrington Park, London, N12 9PN
REGION: East London, England, London, North London, South London, United Kingdom, West London
PAYMENT: Private Pay
DETOX: True
GENDER: mixed
RATING: CQC - Inadequate
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Yoga, Acupuncture, Schema Therapy, Relapse Prevention, Hypnotherapy, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SUMMARY: This North London residential centre offers personalised addiction treatment for alcohol, drugs, and mental health issues, with a flexible approach that goes beyond traditional 12-step methods to include therapies like cognitive behavioural therapy, mindfulness, yoga, and schema therapy. The clinic focuses on equipping you with practical life skills alongside recovery support, and provides on-site detoxification for those who need it. It's best suited to people seeking a tailored, holistic treatment plan in a mixed-gender setting.

---

NAME: Turning Point – Stanfield House
WEBSITE: https://www.turning-point.co.uk/
ADDRESS: 4 Stainburn Road, Cumbria, CA14 4EA
REGION: England, North West, United Kingdom, Workington
PAYMENT: Insurance, Local Authority, NHS, Private Pay
GENDER: mixed
MIN_AGE: 60
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, Motivational Interviewing, Yoga, Meditation, Acupuncture, Relapse Prevention, Group Therapy
TREATS: Alcohol Addiction, Cannabis Addiction, Cocaine, Drug Addiction, Ecstasy, Opioid
ACCESSIBILITY: Men, Women
SETTING: suburban
CAPACITY: 12 beds
SUMMARY: This residential rehabilitation centre in Cumbria offers a structured 12-bed programme for adults dealing with drug and alcohol dependence, combining talking therapies like cognitive behavioural therapy with complementary approaches such as yoga and acupuncture to support your recovery. The first three months focus heavily on one-to-one key working and group therapy sessions to build a strong foundation for your journey towards independence. It's a good choice if you're looking for a mixed-gender setting that blends evidence-based psychological treatment with holistic wellness support.

---

NAME: The Priory Hospital Chelmsford
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-chelmsford/
ADDRESS: The Priory Hospital Chelmsford The Priory Hospital Chelmsford, Essex Stump Lane, Springfield Green, Springfield, Essex, CM1 7SJ
REGION: Bedford, Cambridge, Chelmsford, Crawley, East London, East of England, England, Essex, Guildford, Hertfordshire, High Wycombe, Ipswich, Kent, Maidstone, Margate, Norfolk, Norwich, South East, Suffolk, Sussex, United Kingdom
PAYMENT: Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
DETOX: True
GENDER: men_only
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, 12-Step, Mindfulness, Family Therapy, Psychoeducation, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction, Video Game Addiction
SETTING: city
CAPACITY: 50 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This men-only rehab centre in Essex offers comprehensive treatment for alcohol and drug addiction alongside mental health conditions in a peaceful Grade II listed building with private gardens. The team of specialist doctors, therapists and nurses work together to deliver personalised care through evidence-based therapies including cognitive behavioural therapy, dialectical behaviour therapy and family work, with detoxification available on site. It's a good choice if you're looking for a calm, structured environment where your physical health and emotional wellbeing are both priorities.

---

NAME: New Oakwood Lodge (Phoenix Futures)
WEBSITE: https://www.phoenix-futures.org.uk/phoenix-futures-for/people-and-families-who-use-our-services/find-a-service/new-oakwood-lodge-derby/
ADDRESS: linics New Oakwood Lodge (Phoenix Futures) New Oakwood Lodge (Phoenix Futures), Derby Morley Road, Oakwood, Derbyshire, DE21 4TB
REGION: Derbyshire, East Midlands, England, Lincoln, Nottingham, United Kingdom
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Gym, Group Therapy
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction
TYPE: 12 Step, CBT, Residential
SETTING: rural
CAPACITY: 38 beds
AFTERCARE: Yes
SUMMARY: This Derbyshire residential centre offers structured recovery programmes in a therapeutic community setting where daily routines, peer support and activities work together to help people overcome drug and alcohol dependency. The team use evidence-based approaches including cognitive behavioural therapy and group work, alongside practical support like gym facilities, and it's rated Good by the CQC. It's a welcoming mixed-gender environment that suits people who benefit from a supportive community approach to their recovery.

---

NAME: St Anne’s Alcohol Services, Leeds
WEBSITE: https://www.st-annes.org.uk/
ADDRESS: 186 Woodhouse Lane , West Yorkshire, LS2 9DX
REGION: Darlington, Durham, England, Gateshead, Leeds, Middlesbrough, Newcastle upon Tyne, North East, North West, Salford, Scarborough, Sheffield, Stoke-on-Trent, Sunderland, United Kingdom, Yorkshire and the Humber
COST: Budget-friendly Rehab
PAYMENT: Local Authority, NHS, Private Pay
GENDER: men_only
RATING: CQC - Outstanding
THERAPIES: Cognitive Behavioural Therapy, Motivational Enhancement, 12-Step, SMART Recovery, Yoga, Acupuncture, Group Therapy
TREATS: Alcohol Addiction, Behavioural Addiction, Cocaine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Multi-Substance Addiction, Opioid, Prescription Drug Addiction, Substances Addiction
TYPE: Residential
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: suburban
CAPACITY: 23 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This men-only centre in Leeds has been helping people recover from alcohol dependency since 1976 and was the first of its kind to offer community-based detox in the UK. You'll benefit from experienced specialists who provide safe, structured treatment using a range of therapies including cognitive behavioural therapy, motivational enhancement and 12-step support, alongside complementary approaches like yoga and acupuncture. It's an affordable option with an Outstanding CQC rating, making it a trusted choice if you're looking for proven, accessible rehabilitation close to home.

---

NAME: The Providence Projects
WEBSITE: https://www.providenceproject.org/
ADDRESS: 17 Carysfort Road, Dorset, BH1 4EJ
REGION: Bournemouth, England, Hampshire, Portsmouth, Southampton, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
FAITH: Christian
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Family Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Multi-Substance Addiction, Substances Addiction
ACCESSIBILITY: LGBTQ+ Friendly, Men, Non English Speakers, Pregnant Women, Women
SETTING: coastal
CAPACITY: 44 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
PRICING: apse Prevention Starting From £ 1,400 Per Week Flat Costs Per Week Learn Additional Life Skills Relapse Preven
SUMMARY: This Bournemouth-based centre has been helping people recover from alcohol, drugs, and gambling since 1996, with a track record of supporting over 10,000 people on their journey. They combine proven therapies like cognitive behavioural therapy and mindfulness with family support, and their staff are among the most experienced addiction specialists in the UK. If you're looking for affordable, evidence-based treatment in a welcoming Christian environment where your loved ones can be involved in your recovery, this centre is worth considering.

---

NAME: Littledale Hall Therapeutic Community
WEBSITE: https://www.littledaleaddictionservices.co.uk/
ADDRESS: ale Hall Therapeutic Community Littledale Hall Therapeutic Community, Lancaster Littledale Hall, Littledale Lancashire, LA2 9EY
REGION: England, Lancashire, United Kingdom, Workington
GENDER: mixed
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Mindfulness, Relapse Prevention, Swimming
CAPACITY: 33 beds
SUMMARY: This 33-bed residential centre near Lancaster offers drug and alcohol addiction treatment for adults in a peaceful countryside setting within 200 acres of private land, with programmes lasting between 3 to 12 months tailored to your individual needs. The therapeutic community approach combines talking therapies like cognitive behavioural therapy and mindfulness with practical daily support from counsellors, social workers and dedicated staff members. It's particularly suited to people who want an immersive, supportive environment away from city life where they can focus on recovery with professional guidance every step of the way.

---

NAME: The Priory Hospital Hayes Grove
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-hayes-grove/
ADDRESS: nt Home Clinics The Priory Hospital Hayes Grove The Priory Hospital Hayes Grove, Kent Prestons Road, Hayes Grove, Kent, BR2 7AS
REGION: Bromley, England, London, Sittingbourne, United Kingdom
PAYMENT: Insurance, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Healix
DETOX: True
GENDER: mixed
FAITH: Christian
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction
SETTING: rural
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This private hospital in Bromley offers residential treatment for addiction and mental health conditions like depression, anxiety and eating disorders, with the option to stay as an inpatient or attend day programmes depending on what suits you. What sets it apart is that it tackles both substance misuse and the underlying mental health issues that often come with it, using a range of talking therapies, yoga and other complementary treatments. It's part of the well-established Priory Group and has been rated Good by the CQC, making it a solid choice if you need comprehensive support for addiction alongside other mental health concerns.

---

NAME: Phoenix Futures – Ophelia House, Oxford
WEBSITE: https://www.phoenix-futures.org.uk/phoenix-futures-for/people-and-families-who-use-our-services/find-a-service/ophelia-house/
REGION: Crawley, England, Guildford, High Wycombe, Oxfordshire, South East, Sussex, United Kingdom
COST: Budget-friendly Rehab
PAYMENT: Local Authority, Private Pay
GENDER: women_only
MIN_AGE: 18
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Trauma-Informed, Relapse Prevention, Group Therapy
TREATS: Alcohol Addiction, Cocaine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Multi-Substance Addiction, Opioid, Prescription Drug Addiction
TYPE: Residential
ACCESSIBILITY: Women
SETTING: suburban
CAPACITY: 22 beds
SUMMARY: This women-only residential centre in Oxford offers a safe, supportive environment for women recovering from drug and alcohol addiction through abstinence-based treatment. You'll benefit from personalised care combining therapy, group sessions, and complementary approaches, with particular strength in supporting survivors of domestic violence and trauma. It's a good choice if you're looking for specialist women's healthcare and affordable treatment options in a therapeutic community setting.

---

NAME: Broadway Lodge
WEBSITE: https://www.broadwaylodge.org.uk/
ADDRESS: 37 Totterdown Lane, North Somerset, BS24 9NN
REGION: Bristol, Burnham-on-Sea, Burton upon Trent, Cirencester, Crawley, England, Guildford, Slough, Somerset, South East, South West, Sussex, Swindon, United Kingdom, Weston-super-Mare
PAYMENT: Government Funded, Local Authority, Private Pay
DETOX: True
GENDER: mixed
MIN_AGE: 50
RATING: CQC - Good
THERAPIES: Eye Movement Desensitization, 12-Step, Mindfulness, Yoga, Reiki, Acupuncture, Auricular Acupuncture, Massage, Trauma Therapy, Psychoeducation, Relapse Prevention, Codependency, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
SETTING: suburban
CAPACITY: 42 beds
FAMILY_PROGRAMME: Yes
SUMMARY: This long-established rehab centre near Weston-super-Mare has been supporting people in recovery since 1974 and welcomes everyone regardless of how they'll pay for treatment. You'll find a wide range of therapies on offer, from traditional approaches like counselling and 12-step support to complementary treatments such as yoga, acupuncture and massage, plus expert help with detox if you need it. It's a good fit if you're struggling with alcohol, drugs, gambling, gaming or relationship patterns and want a thorough, rounded approach to getting well.

---

NAME: Cherry Tree Cottage
WEBSITE: https://www.newleafrecovery.co.uk/
ADDRESS: 16 Flint Green Road, Acocks Green, West Midlands, B27 6QA
REGION: England, United Kingdom, West Midlands
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Motivational Interviewing, 12-Step, Mindfulness, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
SETTING: suburban
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This private Birmingham rehab centre offers a warm, supportive environment where adults can recover from alcohol and drug addiction alongside treatment for related mental health needs. You'll benefit from a full range of therapies including one-to-one counselling, cognitive behavioural therapy, mindfulness and yoga, all delivered by a team committed to helping you feel safe and encouraged throughout your stay. The centre is CQC regulated and rated Good, making it a trustworthy choice if you're looking for structured residential treatment in the West Midlands.

---

NAME: Allington House
WEBSITE: https://www.streetscene.org.uk/
ADDRESS: 46 Dean Park Road, Dorset, BH1 1QA
REGION: Bournemouth, Crawley, England, Guildford, Hampshire, Portsmouth, South East, South West, Southampton, Sussex, United Kingdom
PAYMENT: Local Authority, Private Pay
DETOX: True
GENDER: mixed
FAITH: Spiritual (non-denominational)
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Motivational Interviewing, 12-Step, Trauma-Informed, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Substances Addiction, Tramadol, Valium, Xanax
TYPE: Residential
ACCESSIBILITY: LGBTQ+ Friendly, Men, Pregnant Women, Women
SETTING: suburban
CAPACITY: 13 beds
AFTERCARE: Yes
SUMMARY: This Bournemouth rehab centre provides structured, clinically-led treatment for adults struggling with alcohol and drug dependency, using proven therapies like cognitive behavioural therapy and trauma-informed care to help people build lasting recovery. As part of the established Streetscene network, it offers on-site detoxification alongside group and one-to-one support tailored to individual needs. It's a good fit for anyone ready to take a serious step towards change and looking for a welcoming, mixed-gender environment with a spiritual (but non-denominational) foundation.

---

NAME: The Priory Hospital Woodbourne
WEBSITE: https://www.priorygroup.com/locations/priory-hospital-woodbourne-birmingham/
ADDRESS: 21 Woodbourne Road, Edgbaston, West Midlands, B17 8BY
REGION: Altrincham, Coventry, Derbyshire, England, Herefordshire, North West, Staffordshire, United Kingdom, Walsall, Warwick, West Midlands, Worcestershire
PAYMENT: Insurance, NHS, Private Pay
INSURANCE: Vitality, Cigna, WPA, Healix
DETOX: True
GENDER: men_only
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, Dialectical Behaviour Therapy, 12-Step, Mindfulness, Art Therapy, Yoga, Acupuncture, Family Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Behavioural Addiction, Drug Addiction, Gambling Addiction, Internet & Social Media, Multi-Substance Addiction, Prescription Drug Addiction, Sex Addiction, Substances Addiction
ACCESSIBILITY: Men, Non English Speakers, Pregnant Women, Women
SETTING: suburban
CAPACITY: 7 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This long-established Birmingham hospital specialises in treating men with substance misuse alongside mental health conditions like anxiety, depression and trauma, with both NHS and private clients welcome. You'll find a full range of therapies here, from talking treatments to yoga and art therapy, plus on-site detoxification if you need it. It's particularly suited to those who need psychiatric care alongside addiction treatment, as it's the only facility in the region with its own intensive care ward for this combination of needs.

---

NAME: Brynawel Rehab
WEBSITE: https://www.brynawel.org/
ADDRESS: nt Home Clinics Brynawel Rehab Brynawel Rehab, Rhondda Cynon Taff, Wales Llanharry Road, Llanharan, Rhondda Cynon Taff, CF72 9RN
REGION: Colwyn Bay, Newport, Pontypridd, Rhondda Cynon Taff, Swansea, United Kingdom, Wales
GENDER: mixed
RATING: Care Inspectorate Wales - Excellent
THERAPIES: Cognitive Behavioural Therapy, Yoga, Acupuncture, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Drug Addiction, Multi-Substance Addiction, Prescription Drug Addiction
SETTING: rural
SUMMARY: This long-established Welsh rehab centre is the only one in Wales offering specialist treatment for alcohol-related brain damage, making it ideal if you need expert care for complex addiction combined with cognitive issues. You'll benefit from a range of therapies including counselling, cognitive behavioural therapy, yoga and acupuncture, delivered by a team that's earned an Excellent rating from Care Inspectorate Wales. The centre welcomes people from across the UK and treats both alcohol and drug addiction in a mixed-gender setting.

---

NAME: Birchwood @ Kaleidoscope House
WEBSITE: https://birchwood-detox-rehab.com/
ADDRESS: Home Clinics Birchwood @ Kaleidoscope House Birchwood @ Kaleidoscope House, Merseyside Broad Lane, Hewall, Merseyside, CH60 9JY
REGION: England, United Kingdom
DETOX: True
GENDER: mixed
MIN_AGE: 50
RATING: CQC - Requires Improvement
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Art Therapy, Relapse Prevention, Group Therapy, One-to-One Counselling
CAPACITY: 25 beds
SUMMARY: This 25-bed residential centre in Heswall offers a calm, structured approach to drug and alcohol recovery with medical detox on site and a range of therapies including cognitive behavioural therapy, mindfulness and art therapy. The team combines clinical expertise with peer mentors who have personal experience of recovery, providing both professional support and real-world understanding. It suits people looking for a safe, therapeutic environment where they can rebuild their lives with a mix of one-to-one counselling and group support.

---

NAME: Yeldall Manor, Berkshire
WEBSITE: https://www.yeldall.org.uk/
ADDRESS: , Berkshire Budget-friendly Rehab Yeldall Manor, Hare Hatch, Berkshire Yeldall Manor, Bear Lane, Hare Hatch, Berkshire, RG10 9XR
REGION: Altrincham, Berkshire, East Midlands, England, Hampshire, Hemel Hempstead, Lincoln, North West, Nottingham, Oxford, Reading, Slough, United Kingdom
DETOX: False
GENDER: men_only
FAITH: Christian
MIN_AGE: 40
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Relapse Prevention, Gym, Swimming, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Amphetamine, Benzodiazepine, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Substances Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: Men
SETTING: suburban
SUMMARY: This long-established men's rehab centre near Reading has been supporting recovery from alcohol and drug addiction for over 40 years, built on Christian values and run as a registered charity. The centre focuses on helping you rebuild confidence and purpose in life alongside achieving abstinence, using therapies like cognitive behavioural therapy, counselling and 12-step support. Yeldall Manor is CQC-regulated and suits men from any background who are ready to commit to lasting change.

---

NAME: Fleming House
WEBSITE: https://www.anatreatmentcentres.com/
ADDRESS: Home Clinics Fleming House Fleming House (ANA Treatment Centres), Hampshire Fleming House, Waterworks Road, Hampshire, PO6 1NJ
REGION: Basingstoke, Crawley, England, Guildford, Hampshire, High Wycombe, South East, Sussex, United Kingdom
PAYMENT: Private Pay
GENDER: mixed
RATING: CQC - Good
THERAPIES: Cognitive Behavioural Therapy, 12-Step, Mindfulness, Relapse Prevention, Group Therapy, One-to-One Counselling
TREATS: Alcohol Addiction, Cocaine, Drug Addiction, Ecstasy, Heroin, Multi-Substance Addiction, Prescription Drug Addiction, Substances Addiction
TYPE: Residential
SETTING: coastal
CAPACITY: 29 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: Fleming House is a well-established residential centre in Hampshire that supports adults through the full journey of recovery from drug and alcohol addiction, starting with detoxification and moving through to longer-term rehabilitation. The centre uses a range of proven therapies including cognitive behavioural therapy, counselling and mindfulness, and is particularly known for helping people achieve strong completion rates and lasting recovery outcomes. It's a good fit if you're looking for comprehensive, structured treatment in a mixed-gender setting with ongoing support after you leave, including free drop-in aftercare sessions.

---

NAME: Castle Craig, Scotland
WEBSITE: https://www.castlecraig.co.uk/
ADDRESS: ntent Home Clinics Castle Craig, Scotland Castle Craig, West Linton, Scotland Castle Craig, Blythe Bridge, West Linton, EH46 7DH
REGION: Aberdeen, Belfast, Dundee, Dunfermline, East Kilbride, Edinburgh, Erskine, Glasgow, Hamilton, Inverness, Kilmarnock, Kirkcaldy, Lisburn, Livingston, Londonderry, Newry, Northern Ireland, Paisley, Perth, Scotland, Stirling, United Kingdom, West Linton
COST: Premium Rehab
PAYMENT: Charity Funded, Insurance, Local Authority, NHS, Payment Plans, Private Pay
INSURANCE: Bupa, AXA Health, Vitality, Aviva, Cigna, WPA, Aetna, Allianz, Healix
DETOX: True
GENDER: mixed
FAITH: Christian
MIN_AGE: 40
RATING: Healthcare Improvement Scotland - Good
THERAPIES: Cognitive Behavioural Therapy, Eye Movement Desensitization, Motivational Interviewing, 12-Step, Yoga, Acupuncture, Trauma-Informed, Relapse Prevention, Group Therapy, Individual Counselling
TREATS: Alcohol Addiction, Amphetamine, Behavioural Addiction, Benzodiazepine, Cannabis Addiction, Cocaine, Codeine, Crystal Meth, Drug Addiction, Ecstasy, Gambling Addiction, Heroin, Ketamine, Morphine, Multi-Substance Addiction, Opioid, Oxycontin, Prescription Drug Addiction, Substances Addiction, Tramadol, Valium, Xanax
ACCESSIBILITY: LGBTQ+ Friendly, Men, Non English Speakers, Pregnant Women, Women
SETTING: rural
CAPACITY: 100 beds
AFTERCARE: Yes
FAMILY_PROGRAMME: Yes
SUMMARY: This long-established Scottish centre has been helping people recover from addiction since 1988 and remains one of Europe's leading residential rehab facilities, still run by its founding family with a strong commitment to dignity and respect. The programme combines proven therapies like cognitive behavioural therapy, trauma-informed care and the 12-step approach alongside complementary treatments such as yoga and acupuncture, with detoxification available on site. It suits people seeking compassionate, comprehensive treatment in a safe environment where their recovery is the priority.`;
